syntax on
set tabstop=2
set shiftwidth=2
set expandtab

set autoindent
set nosmartindent
set nocindent
filetype indent off
filetype plugin off

set clipboard=unnamedplus

set nomodeline

set listchars=eol:¶,space:·,tab:-->,nbsp:#
highlight NonText ctermfg=darkgray
highlight SpecialKey ctermfg=darkgray

inoremap <silent> <CR> <CR>x<BS>
nnoremap <silent> o ox<BS>
nnoremap <silent> O Ox<BS>

" Alter the behavior of space to strip trailing whitespace from the line
function! g:VimrcClearTrailingWhitespace()
  s/\s*$//
endfunction
noremap <silent> <Space> :call g:VimrcClearTrailingWhitespace()<CR>
noremap <silent> g<Space> :%call g:VimrcClearTrailingWhitespace()<CR>

" Add common blackboard bold symbols to digraphs
digraphs NN 8469 ZZ 8484 QQ 8474 RR 8477 CC 8450

set bg=dark

set number
set relativenumber
set numberwidth=6
highlight LineNr ctermfg=darkmagenta
highlight CursorLineNr ctermfg=magenta
