syntax on
set tabstop=2
set shiftwidth=2
set expandtab

set autoindent
set nosmartindent
set nocindent
filetype indent off
filetype plugin off

set clipboard=unnamedplus

set listchars=eol:¶,space:·,tab:-->,nbsp:#
highlight NonText ctermfg=darkgray
highlight SpecialKey ctermfg=darkgray

inoremap <CR> <CR>x<BS>
nnoremap o ox<BS>
nnoremap O Ox<BS>

set bg=dark

set number
set relativenumber
set numberwidth=6
highlight LineNr ctermfg=darkmagenta
highlight CursorLineNr ctermfg=magenta
