syntax on
set tabstop=2
set shiftwidth=2
set expandtab

set autoindent
set nosmartindent
set nocindent
filetype indent off
filetype plugin off

set clipboard=unnamedplus

set nomodeline

set listchars=eol:¶,space:·,tab:-->,nbsp:#
highlight NonText ctermfg=darkgray
highlight SpecialKey ctermfg=darkgray

inoremap <silent> <CR> <CR>x<BS>
nnoremap <silent> o ox<BS>
nnoremap <silent> O Ox<BS>

" Alter the behavior of space to strip trailing whitespace from the line
function! g:VimrcClearTrailingWhitespace()
  s/\s*$//
endfunction
noremap <silent> <Space> :call g:VimrcClearTrailingWhitespace()<CR>
noremap <silent> g<Space> :%call g:VimrcClearTrailingWhitespace()<CR>

set bg=dark

set number
set relativenumber
set numberwidth=6
highlight LineNr ctermfg=darkmagenta
highlight CursorLineNr ctermfg=magenta

" --- Asynchronous Lint Engine (ALE) Config ---

let g:ale_lint_on_enter            = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save             = 1
let g:ale_lint_on_text_changed     = 1
let g:ale_lint_on_insert_leave     = 1
let g:ale_lint_delay               = 500

let g:ale_linters_explicit = 1
let g:ale_linters = {
\   'rust': ['analyzer']
\}

let g:ale_set_signs = 0

let g:ale_virtualtext_prefix = '✗ ⟨%type%⟩ '
let g:ale_echo_cursor = 0

let g:ale_default_navigation = 'tab'

let g:ale_floating_preview = 1
let g:ale_floating_window_border = [
\   '┃', '━',
\   '┏', '┓', '┛', '┗',
\   '┃', '━'
\]
highlight clear Pmenu

nnoremap <silent> <F2> :ALEHover<CR>

inoremap <silent><expr> <Tab>
\   pumvisible() ? "\<C-y>" : "\<Tab>"
inoremap <silent><expr> <CR>
\   pumvisible() ? "\<C-e>\<CR>x\<BS>" : "\<CR>x\<BS>"

set completeopt=menu,noinsert
set omnifunc=ale#completion#OmniFunc
inoremap <silent> <S-Tab> <C-X><C-O>
