[window]
padding.x = 5
padding.y = 5
dynamic_padding = true
resize_increments = true

[font]
normal.family = "Fira Code"
normal.style  = "SemiBold"

bold.style = "Bold"
italic.style = "Italic"
bold_italic.style = "Bold Italic"

size = 9

[colors]

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[keyboard]
bindings = [
    { mode = "Vi", key = "PageUp",   action = "ScrollHalfPageUp"   },
    { mode = "Vi", key = "PageDown", action = "ScrollHalfPageDown" },
    { key = "PageUp",   mods = "Shift", action = "ScrollHalfPageUp"   },
    { key = "PageDown", mods = "Shift", action = "ScrollHalfPageDown" },
]
